# Generated by Django 5.2.9 on 2025-12-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(default=0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('joined_months_ago', models.IntegerField(default=0)),
                ('sessions_count', models.IntegerField(default=0)),
                ('price_60_min', models.IntegerField()),
                ('price_30_min', models.IntegerField()),
                ('image', models.URLField(blank=True, null=True)),
                ('certificates', models.JSONField(blank=True, default=list)),
                ('available_days', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
