# Generated by Django 5.2.9 on 2026-06-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sub_specialty', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('area', models.CharField(blank=True, db_index=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews_count', models.IntegerField(default=0)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('vezeeta_url', models.URLField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-rating', '-reviews_count'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='partial', max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('saved', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('deactivated', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
