# Generated by Django 5.2.9 on 2026-07-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='emotion',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('tired', 'Tired'), ('scared', 'Scared'), ('surprise', 'Surprise'), ('love', 'Love'), ('angry', 'Angry'), ('nervous', 'Nervous'), ('shy', 'Shy'), ('excited', 'Excited'), ('bored', 'Bored'), ('silly', 'Silly'), ('worried', 'Worried'), ('sick', 'Sick')], max_length=16),
        ),
    ]
